/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Test;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void testQuoteAPIData() throws IOException {
        URL quote1 = new URL("https://favqs.com/api/qotd");
        HttpURLConnection quoteCon = (HttpURLConnection) quote1.openConnection();
        quoteCon.setRequestMethod("GET");
        int responseCode = quoteCon.getResponseCode();
        assertTrue(responseCode == 200);

        InputStreamReader reader = new InputStreamReader(quoteCon.getInputStream());
        BufferedReader quoteReader = new BufferedReader(reader);
        String quoteData = quoteReader.readLine();
        assertTrue(!quoteData.isEmpty());
        reader.close();
    }





}
