/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;


class AppTest {
    @Test
    public void testGetRandomQuote() {
        Quote quote = new Quote();
        String randomQuote = quote.getRandomQuote();
        Assertions.assertNotNull(randomQuote);
        Assertions.assertFalse(randomQuote.isEmpty());
    }
}
