/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

public class App {


    public static void main(String[] args) {
        Quote quote = new Quote();
        System.out.println("1/"+quote.getRandomQuote());
        System.out.println("2/"+quote.getRandomQuote());
    }
}
